config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/loggedin'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  
  post '/signup' => 'splash#signup', as: :splash_signup
  get '/splash' => 'splash#index'
  root 'splash#index'
  get '/setup' => 'setup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate

  def index
  end

  def signup
    if ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'].blank? or ENV['MAILCHIMP_API_KEY'].blank?

      @message = "The MAILCHIMP_API_KEY and MAILCHIMP_SPLASH_SIGNUP_LIST_ID environment variables need to be set for mailing list signup to work! If you don't want this feature, you can just remove the mailing list signup feature from app/views/splash/index.html.haml"

    else
      begin

        gb = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])

       gb.lists(ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID']).members.create(
         body: {
           email_address: params[:signup_email],
           status: "pending"
           }
         )

        @message = 'Thanks for signing up!'

      rescue StandardError => e
        @error = true

        if e.message =~ /is already subscribed to the list/
          @message = "You're already signed up to receive updates. Thanks for your enthusiasm!"
        else
          @message = "Oops! Looks like we ran into an error. How embarrassing. Please try again later!"
        end

      end
    end
  end


  private

    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

end

app/views/splash/_environment_checks.html.haml
%ul.list-group

  - if ENV['AWS_ACCESS_KEY_ID'].blank? or ENV['AWS_SECRET_ACCESS_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 AWS
      You haven't set up your AWS account in this environment! Set the <code>AWS_ACCESS_KEY_ID</code> and <code>AWS_SECRET_ACCESS_KEY</code> environment variables to configure AWS. You should have the client sign up and follow the instructions below.
  - else
    %li.list-group-item.list-group-item-success
      %h4 AWS
      Your AWS account is configured for this environment!



  - if ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Google Analytics
      You haven't set up a Google Analytics account in this environment! Set the <code>GOOGLE_ANALYTICS_SITE_ID</code> environment variables to configure Google Analytics. You should ask the client to <a href="http://google.com/analytics/" target="_blank">set up a Google Analytics account</a>.
  - else
    %li.list-group-item.list-group-item-success
      %h4 Google Analytics
      Your Google Analytics account is configured for this environment!



  - unless @tracker_gems.values.any?
    %li.list-group-item.list-group-item-danger
      %h4 Exception Tracking
      You haven't set up an exception tracker! May I recommend <a href="https://addons.heroku.com/honeybadger" target="_blank">Honeybadger</a>?
  - else
    %li.list-group-item.list-group-item-success
      %h4 Exception Tracking
      Found exception tracker gems(s):
      = @tracker_gems.select{|k,v| v}.keys.join(', ')



  - if ENV['MAILCHIMP_API_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Mailchimp
      <p>You haven't set up a Mailchimp account in this environment! Have the client create an account at <a href="http://mailchimp.com" target="_blank">mailchimp.com</a> and set the <code>MAILCHIMP_API_KEY</code> environment variables to configure Mailchimp.</p>
      <p>Once a Mailchimp account is configured, you'll need to create a list through the web interface and set the <code>MAILCHIMP_SPLASH_SIGNUP_LIST_ID</code> environment variable to the list id (ten-digit hex id visible in the List name &amp; defaults tab).</p>
  - else
    %li.list-group-item.list-group-item-success
      %h4 Mailchimp
      Your Mailchimp account is configured for this environment!

app/views/splash/index.html.haml
%section.lightimage
  .container
    .row
      .inner-column
        %h1 Big Fat Title

        %p.info Great descriptive content

        = link_to "Call to Action", root_url, class: "btn btn-primary btn-lg"

%section.colored.primary#about
  .container
    .row
      .inner-column
        %h2 Question I'm about to answer?

        %p Why yes, this is the answer.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.  And it goes on for a bit.

        = link_to "Another call to action", root_url, class: "btn btn-primary-inverted btn-lg"

%section.features#features
  .container
    .row
      .inner-block
        = image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic1.jpg", class: "img-responsive"
        %h4 SPROUTS
        %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one.

      .inner-block
        = image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic2.jpg", class: "img-responsive"
        %h4 COUNTER CULTURE
        %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one.

      .inner-block
        = image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic3.jpg", class: "img-responsive"
        %h4 BIKE SANDWICH
        %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one. 

      .inner-block
        = image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic2.jpg", class: "img-responsive"
        %h4 COUNTER CULTURE
        %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one.

%section.images
  .quarter-block
    = image_tag "https://scontent-lga3-1.cdninstagram.com/t51.2885-15/e35/12237401_1672681199644836_991083135_n.jpg"

  .quarter-block
    = image_tag "https://scontent-lga3-1.cdninstagram.com/t51.2885-15/e35/12716797_1679687052302598_977732638_n.jpg"
  .quarter-block
    = image_tag "https://scontent-lga3-1.cdninstagram.com/t51.2885-15/e35/12107643_1510048632656460_2102141939_n.jpg"
  .quarter-block
    = image_tag "https://scontent-lga3-1.cdninstagram.com/t51.2885-15/e35/12237446_1702630963356665_284108057_n.jpg"

            
%section.contact#contact
  .container
    .row
      .inner-column
        %h1 Stay connected for announcements and releases.
        = form_tag splash_signup_path, role: :form, remote: true do
          .form-group
            .input-group
              = text_field_tag :signup_email, "", class: "form-control", placeholder: 'E-Mail', type: "email"
              %span.input-group-btn
                = submit_tag 'Sign up', class: 'btn btn-primary'
          %small#signup-message

app/views/splash/signup.js.erb
<% if @error %>
  $('#signup').addClass('has-error');
<% else %>
  $('#signup').removeClass('has-error');
  $('#signup_email').val('');
<% end %>

$('#signup-message').text("<%= j @message.html_safe %>").hide().slideDown('fast');